#define VERSION_NUM1 13
#define VERSION_NUM2 8

#define STRINGIZER_HELPER(a) #a
#define STRINGIZER(a) STRINGIZER_HELPER(a)

#define VERSION_NUMS VERSION_NUM1,VERSION_NUM2
#define VERSION_STRING STRINGIZER(VERSION_NUM1) "." STRINGIZER(VERSION_NUM2)

#define VERSION_STRING_WITH_V "v" VERSION_STRING

#define RC_VERSION_STRING(num1,num2) STRINGIZER(num1) "." STRINGIZER(num2)
